---
- name: Pull and run Docker image mdhiadhia/app-pipeline:latest
  hosts: app
  tasks:

    - name: Stop Docker container if it is running
      command: docker stop app_pipeline
      ignore_errors: yes

    - name: Remove Docker container if it exists
      command: docker rm app_pipeline
      ignore_errors: yes

    - name: Pull Docker image mdhiadhia/app-pipeline from  pferegestery.azurecr.io
      command: docker pull  pferegestery.azurecr.io/mdhiadhia/app-pipeline:latest

    - name: Run Docker container from mdhiadhia/app-pipeline image
      command: docker run -d -p 4200:80 --name app_pipeline mdhiadhia/app-pipeline:latest
